vich_uploader:
    db_driver: orm

    mappings:
        avatar_image:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        property_image:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true